POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "An algorithm is a sequence of steps to solve a problem",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": 1,
    "important": "yeah"
}